name: CI - Test microservizio
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codice
        uses: actions/checkout@v4
      
      - name: Install docker-compose
        run: |
          sudo curl -L \
            "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64" \
            -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version
      
      - name: Avvia servizi Docker compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Attendi inizializzazione DB
        run: sleep 10

      - name: Inizializza il DB
        run: docker-compose -f docker-compose.yml exec microservizio python init_db.py

      - name: Esegui i test
        run: docker-compose -f docker-compose.yml exec microservizio pytest

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
          docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Docker build
        run: docker build -t dpetza/lezione15 .

      - name: Docker push
        run: docker push dpetza/lezione15

      - name: Cleanup finale
        run: docker-compose -f docker-compose.yml down -v